name: Github Workflows Security Analysis (Zizmor) (self)

on:
  pull_request:

permissions:
  contents: read
  packages: read

jobs:
  dependency-review:
    uses: ./.github/workflows/zizmor.yml
    permissions:
      security-events: write

